module.exports = {
	parserOptions: {
		ecmaFeatures: {
			jsx: true,
		},
	},
	plugins: ['react'],
	settings: {
		react: {
			version: '16.4',
		},
	},
	rules: {
		'jsx-quotes': ['error', 'prefer-double'],
		'react/destructuring-assignment': ['error', 'always', { ignoreClassFields: true }],
		'react/display-name': 'error',
		'react/forbid-prop-types': 'off',
		'react/jsx-boolean-value': ['error', 'never'],
		'react/jsx-closing-bracket-location': 'error',
		'react/jsx-curly-spacing': 'error',
		'react/jsx-equals-spacing': 'error',
		'react/jsx-filename-extension': [
			'error',
			{
				extensions: ['.js'],
			},
		],
		'react/jsx-first-prop-new-line': ['error', 'multiline'],
		'react/jsx-handler-names': 'error',
		'react/jsx-indent-props': ['error', 'tab'],
		'react/jsx-key': 'off',
		'react/jsx-max-props-per-line': [
			'error',
			{
				maximum: 3,
			},
		],
		'react/jsx-no-bind': 'off',
		'react/jsx-no-comment-textnodes': 'error',
		'react/jsx-no-duplicate-props': 'error',
		'react/jsx-no-literals': 'off',
		'react/jsx-no-target-blank': 'off',
		'react/jsx-no-undef': 'error',
		'react/jsx-pascal-case': 'error',
		'react/jsx-sort-props': 'off',
		'react/jsx-tag-spacing': [
			'error',
			{
				beforeSelfClosing: 'always',
			},
		],
		'react/jsx-uses-react': 'error',
		'react/jsx-uses-vars': 'error',
		'react/jsx-wrap-multilines': 'error',
		'react/no-danger': 'error',
		'react/no-deprecated': 'error',
		'react/no-did-mount-set-state': 'error',
		'react/no-did-update-set-state': 'error',
		'react/no-direct-mutation-state': 'error',
		'react/no-is-mounted': 'error',
		'react/no-multi-comp': 'off',
		'react/no-render-return-value': 'error',
		'react/no-set-state': 'off',
		'react/no-string-refs': 'error',
		'react/no-typos': 'warn',
		'react/no-unknown-property': 'error',
		'react/no-unescaped-entities': 'error',
		'react/prefer-arrow-callback': 'off',
		'react/prefer-es6-class': 'error',
		'react/prefer-stateless-function': [
			'error',
			{
				ignorePureComponents: true,
			},
		],
		'react/prop-types': 'error',
		'react/react-in-jsx-scope': 'error',
		'react/require-optimization': 'off',
		'react/require-render-return': 'error',
		'react/self-closing-comp': 'error',
		'react/sort-comp': 'error',
		'react/sort-prop-types': 'error',
		'react/style-prop-object': 'error',
		'react/void-dom-elements-no-children': 'error',
	},
};
